language: android

android:
  components:
    - tools
    - tools

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository

jdk:
  - oraclejdk8

sudo: required

script: ./gradlew assemblePlainDebug assemblePlainRelease
